services:
  db:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./DB:/var/lib/postgresql/data
    dns:
      - 8.8.8.8
      - 8.8.4.4

  backend:
    build: ./server
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: 5000
    ports:
      - '5000:5000'
    volumes:
      - ./server:/server
      - ./server/uploads/labs:/server/uploads/labs
      - ./server/uploads/submissions:/server/uploads/submissions
      - ./server/logs:/server/logs
    dns:
      - 8.8.8.8
      - 8.8.4.4
    command: npm run start
